# -*- coding: utf-8 -*-
"""Untitled33.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oGEH790QVb9VMQUKuzFAa6FCdJAyAs3O
"""

import numpy as np
import matplotlib.pyplot as plt

def n(r,Z):
  a = 1
  return 8 * (r**2) * (Z**3)/(a**3) * np.exp(-2*Z*r/a)

r = np.linspace(0,10,1000)

plt.plot(r,n(r,27/16), label=r"$Z_{opt}$")
plt.plot(r,n(r,2), label=r"$Z = 2$")
plt.xlabel(r"$r$")
plt.ylabel(r"$4 \pi r^2n(r)$")
plt.grid()
plt.legend()
plt.savefig("density.png")

